<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>55915558-ecbc-49f0-9389-f4a5fd2471cf</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
	 <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
	  <PackageReference Include="Scalar.AspNetCore" Version="2.6.8" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Estore.Application\Estore.Application.csproj" />
    <ProjectReference Include="..\Estore.Infrastructure\Estore.Infrastructure.csproj" />
  </ItemGroup>

</Project>
